site_name: 輸入法文件存檔

nav:
  - "index.md"
  - "微軟新注音輸入法 98":
      - "ms_new_phonetic_98/index.md"
  - "微軟新倉頡輸入法 98":
      - "ms_new_cangjie_98/index.md"
  - "倚天中文 2000":
      - "et2000/index.md"
      - "et2000_box/index.md"
  - "自然輸入法 99":
      - "going_99/chapt0.md"
      - "going_99/chapt1.md"
      - "going_99/chapt2.md"
      - "going_99/chapt3.md"
      - "going_99/chapt4.md"
      - "going_99/chapt5.md"
      - "going_99/chapt6.md"
      - "going_99/chapt-aa.md"
      - "going_99/chapt-ab.md"
      - "going_99/chapt-ac.md"
      - "going_99/chapt-ad.md"
      - "going_99/chapt-ae.md"
  - "漢音輸入法 macOS 5.0":
      - "hanin_5_macos/hanin_5_readme.md"
      - "hanin_5_macos/keys.md"
  - "漢音輸入法 Windows 5.02":
      - "hanin_5_windows/readme.md"
      - "hanin_5_windows/help.md"
  - "TCIM (macOS 9.2 繁體中文版)":
      - "tcim/index.md"

markdown_extensions:
  - footnotes
  - tables

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
