site_name: 輸入法文件存檔

nav:
  - "index.md"
  - "漢音輸入法 macOS 5.0":
      - "hanin_5_macos/hanin_5_readme.md"
  - "漢音輸入法 Windows 5.02":
      - "hanin_5_windows/readme.md"
      - "hanin_5_windows/help.md"

markdown_extensions:
  - footnotes
  - tables

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
